#!/usr/bin/env node
/**
 * rooms.yaml → generated artefacts.
 *   src/generated/config.ts   typed config baked into the panel bundle
 *   dashboards/generated/*    Lovelace YAML fallback / admin surface
 *   config/packages/*         HA package with the helpers the panels expect
 *
 * Run after every edit to rooms.yaml:  npm run gen
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync, copyFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import YAML from 'yaml';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
/**
 * Resolve the room manifest.
 *
 * `rooms.yaml` describes a specific house and is gitignored, so a fresh clone
 * has only `rooms.example.yaml`. Copy it across on first run rather than
 * failing: the whole project should build straight after `npm install`.
 */
function manifestPath(root) {
  const mine = join(root, 'rooms.yaml');
  if (existsSync(mine)) return mine;
  const example = join(root, 'rooms.example.yaml');
  if (existsSync(example)) {
    copyFileSync(example, mine);
    console.log('  rooms.yaml created from rooms.example.yaml — edit it to describe your house\n');
    return mine;
  }
  throw new Error('no rooms.yaml or rooms.example.yaml found');
}

const man = YAML.parse(readFileSync(manifestPath(ROOT), 'utf8'));

/** Strip the `?` marker used for unverified, convention-guessed entity ids. */
const clean = (e) => (typeof e === 'string' ? e.replace(/\?$/, '') : e);
const unverified = (e) => typeof e === 'string' && e.endsWith('?');

const warnings = [];
const seen = new Map();

function entity(raw, where) {
  if (!raw) return undefined;
  const id = clean(raw);
  if (unverified(raw)) warnings.push(`${where}: ${id} (unverified guess)`);
  if (!/^[a-z_]+\.[a-z0-9_]+$/.test(id)) warnings.push(`${where}: "${id}" is not a valid entity_id`);
  const prev = seen.get(id);
  if (prev && prev !== where) warnings.push(`${id} used by both ${prev} and ${where}`);
  seen.set(id, where);
  return id;
}

const rooms = [...man.rooms]
  .sort((a, b) => (a.order ?? 99) - (b.order ?? 99))
  .map((r) => {
    const e = r.entities ?? {};
    const scenes = (man.scenes ?? []).map((s) => ({
      id: s.id,
      name: s.name,
      icon: s.icon,
      scope: s.scope,
      mood: s.mood ?? { k: 2700, level: 0.6 },
      entity: s.scope === 'house' ? `scene.${s.id}` : `scene.${r.slug}_${s.id}`,
    }));
    return {
      slug: r.slug,
      accent: r.accent ?? '#E0913C',
      name: r.name,
      short: r.short ?? r.name,
      icon: r.icon,
      display: r.display,
      lights: (e.lights ?? []).map((l, i) => ({
        entity: entity(l.entity, `${r.slug}.lights[${i}]`),
        name: l.name,
        kind: l.kind,
      })),
      climate: entity(e.climate, `${r.slug}.climate`),
      media: entity(e.media, `${r.slug}.media`),
      temperature: entity(e.temperature, `${r.slug}.temperature`),
      humidity: entity(e.humidity, `${r.slug}.humidity`),
      scenes,
      wake: r.wake?.enabled ? {
        sleepAt: r.wake.sleep_at ?? '19:30',
        wakeAt: r.wake.wake_at ?? '07:00',
        dawnMinutes: r.wake.dawn_minutes ?? 45,
        morningMinutes: r.wake.morning_minutes ?? 90,
        nightBrightness: r.wake.night_brightness ?? 4,
        dawnBrightness: r.wake.dawn_brightness ?? 35,
        dayBrightness: r.wake.day_brightness ?? 70,
        wakeEntity: `input_datetime.${r.slug}_vaagetid`,
        enabledEntity: `input_boolean.${r.slug}_vaageur`,
      } : undefined,
    };
  });

// ── src/generated/config.ts ────────────────────────────────────────────────
const cfg = {
  meta: man.meta,
  models: man.models,
  theme: man.theme,
  heating: man.heating,
  favourites: man.sonos_favourites ?? [],
  aura: man.sonos_aura ?? ['#4FD08A', '#3C8FD0', '#B478D8'],
  rooms,
};

const ts = `// GENERATED by tools/generate.mjs — DO NOT EDIT.
// Source of truth: rooms.yaml   ·   regenerate with \`npm run gen\`

export interface LightCfg { entity: string; name: string; kind: 'hue' | 'shelly' }
export interface Mood { k?: number; hex?: string; hue2?: string; level: number }
export interface SceneCfg { id: string; name: string; icon: string; scope: 'room' | 'house'; entity: string; mood: Mood }
export interface ThemeCfg {
  mode: 'sun' | 'time' | 'dark' | 'light';
  sun_entity: string;
  light_from: string; light_to: string;
  transition_ms: number;
}
export interface WakeCfg {
  sleepAt: string; wakeAt: string;
  dawnMinutes: number; morningMinutes: number;
  nightBrightness: number; dawnBrightness: number; dayBrightness: number;
  /** optional HA overrides — used when the entities exist */
  wakeEntity: string; enabledEntity: string;
}
export interface RoomCfg {
  slug: string; accent: string; name: string; short: string; icon: string;
  wake?: WakeCfg;
  display: 'wd' | 'xl';
  lights: LightCfg[];
  climate?: string; media?: string; temperature?: string; humidity?: string;
  scenes: SceneCfg[];
}
export interface Budget { max_dom_nodes: number; max_bundle_gz_kb: number; no_blur: boolean; no_photos: boolean }
export interface ModelCfg { label: string; soc: string; canvas: { w: number; h: number; dpr: number }; shell: 'tabs' | 'overview'; budget: Budget }
export interface Config {
  meta: { locale: string; timezone: string; ha_url: string };
  models: Record<'wd' | 'xl', ModelCfg>;
  theme: ThemeCfg;
  heating: { min: number; max: number; step: number; presets: { name: string; temp: number }[] };
  favourites: { name: string; source: string }[];
  aura: string[];
  rooms: RoomCfg[];
}

export const CONFIG: Config = ${JSON.stringify(cfg, null, 2)} as const satisfies Config;

export const roomBySlug = (s: string): RoomCfg | undefined =>
  CONFIG.rooms.find((r) => r.slug === s);

/** Every entity this room's panel subscribes to. */
export function roomEntities(r: RoomCfg): string[] {
  return [
    ...r.lights.map((l) => l.entity),
    r.climate, r.media, r.temperature, r.humidity,
    ...r.scenes.map((s) => s.entity),
  ].filter(Boolean) as string[];
}
`;
mkdirSync(join(ROOT, 'src/generated'), { recursive: true });
writeFileSync(join(ROOT, 'src/generated/config.ts'), ts);

// ── rooms.json — consumed by public/debug.html ────────────────────────────
writeFileSync(
  join(ROOT, 'public/rooms.json'),
  JSON.stringify({ rooms: rooms.map((r) => ({ slug: r.slug, name: r.name, short: r.short, display: r.display, accent: r.accent })) }, null, 2)
);

// ── HA package: helpers the panels rely on ────────────────────────────────
const pkg = {
  homeassistant: {
    customize: {},
  },
  input_boolean: {
    ...Object.fromEntries(
      rooms.map((r) => [`panel_${r.slug}_screensaver`, { name: `Pauseskærm ${r.name}`, icon: 'mdi:monitor' }])
    ),
    // one per room with a sleep clock, so it can be turned off for a sleepover
    ...Object.fromEntries(
      rooms.filter((r) => r.wake).map((r) => [
        `${r.slug}_vaageur`,
        { name: `Vågeur ${r.short}`, icon: 'mdi:weather-sunset-up', initial: true },
      ])
    ),
  },
  input_datetime: Object.fromEntries(
    rooms.filter((r) => r.wake).map((r) => [
      `${r.slug}_vaagetid`,
      { name: `Vågetid ${r.short}`, has_date: false, has_time: true, initial: r.wake.wakeAt },
    ])
  ),
  script: {
    alt_slukket: {
      alias: 'Alt slukket',
      mode: 'single',
      sequence: [
        { action: 'light.turn_off', target: { entity_id: rooms.flatMap((r) => r.lights.map((l) => l.entity)) } },
        { action: 'media_player.media_pause', target: { entity_id: rooms.map((r) => r.media).filter(Boolean) } },
      ],
    },
  },
};
mkdirSync(join(ROOT, 'config/packages'), { recursive: true });
writeFileSync(
  join(ROOT, 'config/packages/hjem_panels.yaml'),
  '# GENERATED by tools/generate.mjs — DO NOT EDIT.\n' +
    '# Add to configuration.yaml:\n#   homeassistant:\n#     packages: !include_dir_named packages\n\n' +
    YAML.stringify(pkg)
);

// ── Kiosk dashboard: one full-bleed iframe per room ───────────────────────
// This is how the panel app reaches a Shelly Wall Display in production. The
// Shelly HA app can open a Home Assistant dashboard but NOT an arbitrary URL,
// so we give it a real Lovelace dashboard whose only content is an iframe
// pointing at /local/hjem/. Panel mode + a webpage card = full screen, no HA
// chrome, and the Shelly app is none the wiser.
const kiosk = {
  title: 'hjem kiosk',
  views: rooms.map((r) => ({
    title: r.short,
    path: r.slug,
    type: 'panel',
    cards: [
      {
        type: 'iframe',
        url: `/local/hjem/index.html?room=${r.slug}`,
        // 100% so the card fills panel mode rather than honouring an aspect ratio
        aspect_ratio: '100%',
      },
    ],
  })),
};
mkdirSync(join(ROOT, 'dashboards/generated'), { recursive: true });
writeFileSync(
  join(ROOT, 'dashboards/generated/hjem_kiosk.yaml'),
  '# GENERATED by tools/generate.mjs — DO NOT EDIT.\n' +
    '# The dashboard each Shelly Wall Display actually opens.\n' +
    '#\n' +
    '# Add to configuration.yaml:\n' +
    '#   lovelace:\n' +
    '#     dashboards:\n' +
    '#       hjem-kiosk:\n' +
    '#         mode: yaml\n' +
    '#         filename: dashboards/generated/hjem_kiosk.yaml\n' +
    '#         title: hjem kiosk\n' +
    '#         show_in_sidebar: false\n' +
    '#\n' +
    '# Then point each panel at:  /hjem-kiosk/<room-slug>\n\n' +
    YAML.stringify(kiosk)
);

// ── Lovelace fallback dashboard (admin / phone surface) ───────────────────
const lovelace = {
  title: 'hjem',
  views: rooms.map((r) => ({
    title: r.short,
    path: r.slug,
    type: 'sections',
    max_columns: 2,
    sections: [
      {
        type: 'grid',
        cards: [
          { type: 'heading', heading: r.name },
          ...r.lights.map((l) => ({ type: 'tile', entity: l.entity, name: l.name, features: [{ type: 'light-brightness' }] })),
          ...(r.climate ? [{ type: 'tile', entity: r.climate, features: [{ type: 'target-temperature' }] }] : []),
          ...(r.media ? [{ type: 'tile', entity: r.media, features: [{ type: 'media-player-volume-slider' }] }] : []),
          ...(r.temperature ? [{ type: 'tile', entity: r.temperature }] : []),
          ...(r.humidity ? [{ type: 'tile', entity: r.humidity }] : []),
        ],
      },
      {
        type: 'grid',
        cards: [
          { type: 'heading', heading: 'Scener' },
          ...r.scenes.map((s) => ({ type: 'button', entity: s.entity, name: s.name, tap_action: { action: 'toggle' } })),
        ],
      },
    ],
  })),
};
mkdirSync(join(ROOT, 'dashboards/generated'), { recursive: true });
writeFileSync(
  join(ROOT, 'dashboards/generated/hjem.yaml'),
  '# GENERATED by tools/generate.mjs — DO NOT EDIT.\n' +
    '# Fallback / admin dashboard. The wall panels do NOT use this — they run\n' +
    '# the standalone app in public/. This exists for phones and for debugging.\n\n' +
    YAML.stringify(lovelace)
);

// ── report ────────────────────────────────────────────────────────────────
const allEntities = rooms.flatMap((r) => [
  ...r.lights.map((l) => l.entity), r.climate, r.media, r.temperature, r.humidity,
]).filter(Boolean);

console.log(`✓ ${rooms.length} rooms · ${allEntities.length} entities · ${rooms[0].scenes.length} scenes/room`);
console.log('  → src/generated/config.ts');
console.log('  → config/packages/hjem_panels.yaml');
console.log('  → dashboards/generated/hjem.yaml');
console.log('  → public/rooms.json');
console.log('  → dashboards/generated/hjem_kiosk.yaml   (what the panels open)');
if (warnings.length) {
  const guesses = warnings.filter((w) => w.includes('unverified')).length;
  const real = warnings.filter((w) => !w.includes('unverified'));
  console.log(`\n  ${guesses} entity ids are unverified guesses — run \`npm run discover\` once HA is up.`);
  if (real.length) { console.log('\n  PROBLEMS:'); real.forEach((w) => console.log('   ! ' + w)); }
}
